#!/bin/bash

set -e

sudo apt-get update

sudo apt-get install -y curl mercurial
sudo apt-get install -y ruby rubygems
sudo gem install fpm-cookery --no-ri --no-rdoc

cd /vagrant/recipes

for recipe in $(find . -maxdepth 2 -type f -name "*.rb")
do
  sudo fpm-cook install-deps "$recipe"
  fpm-cook package "$recipe"
done
